# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_location',
            field=models.CharField(default='City, State', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='My Team', max_length=255),
        ),
    ]
