# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ref',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='ref',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.AddField(
            model_name='ref',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ref',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
