# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='current_team',
            new_name='curr_team',
        ),
    ]
